config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"
  resources :posts do
    resources :comments
  end
  resources :friendships do
    put :confirm
  end
  resources :friend_requests do
    put :confirm
  end
  resources :friends_list
  resources :groups
  resources :members
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :content

  belongs_to :post
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_own_comment, only: [:edit, :update, :destroy]
  def index
    @comments = @post.comments
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.user = current_user
    if @comment.save
      redirect_to post_comments_path(@post)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      redirect_to post_comments_path(@post, @comment)
    else
      render :edit
    end
  end

  def destroy
    if @comment.destroy
      redirect_to post_comments_path(@post)
    end
  end

  private

  def set_post
    @post = Post.find params[:post_id]
  end

  def set_own_comment
    @comment = current_user.comments.find_by_id(params[:id])
    if @comment.nil?
      flash[:alert] = 'this comment is not belongs to you or not exists'
      redirect_to post_comments_path
    end
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/views/comments/edit.html.erb
<%= link_to 'index', posts_path %>

<%= form_for @comment, url: post_comment_path(@post, @comment), method: :patch do |f| %>
  <p><%= f.label :content %></p>
  <p><%= f.text_area :content %></p>
  <%= f.submit %>
<% end %>

app/views/comments/index.html.erb
<%= render "layouts/navbar/sharednav" %>
<div class="w-50 m-auto">
  <%= link_to 'new', new_post_comment_path(@post) %> <br> <br>
  <% @comments.each do |comment| %>
  <label><p>Email : <%= comment.user.email %></p></label> <br>
  <label><p>Content : <%= comment.content %></p></label>
    <div>
      <%= link_to 'edit', edit_post_comment_path(@post, comment)if policy(comment).update? %>
      <%= link_to 'delete', post_comment_path(@post, comment), method: :delete, data: { confirm: "Are you sure?" }if policy(comment).update?%>
    </div>
    <br> <br>
<% end %>

</div>

app/views/comments/new.html.erb
<%= link_to 'index', posts_path %>
<h2>New comment for Post id<%= @post.id %></h2>
<%= form_for @comment, url: post_comments_path(@post), method: :post do |f| %>
  <p><%= f.label :content %></p>
  <p><%= f.text_area :content %></p>
  <%= f.submit %>
<% end %>