config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"
  resources :posts do
    resources :comments
  end
  resources :friendships do
    put :confirm
  end
  resources :friend_requests do
    put :confirm
  end
  resources :friends_list
  resources :groups
  resources :members
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_posts
  has_many :members
  validates :name, :description, :banner, :privacy, presence: true
  enum privacy: [:public_group, :hidden]
  mount_uploader :banner, ImageUploader
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, except: [:index, :new, :create]
  def index

    public_group = Group.public_group
    own_group = current_user.groups.where.not(privacy: :public_group)
    @groups = own_group + public_group
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    if @group.save
      @group.members.create(member_id: current_user.id, role: :admin, user_id: current_user.id, status: "confirmed")
      flash[:notice] = "Group created successfully!"
      redirect_to groups_path
    else
      flash[:alert] = "Group created failed!"
      render :new
    end
  end

  def edit; end

  def update
    if @group.update(group_params)
      flash[:notice] = "Group updated successfully!"
      redirect_to groups_path
    else
      flash[:alert] = "Group failed to edit!"
      render :edit
    end
  end

  def show; end

  def destroy
    if @group.destroy
      flash[:notice] = "Group deleted successfully!"
    else
      flash[:alert] = "Group failed to delete!"
    end
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :description, :banner, :privacy)
  end

  def set_group
    @group = Group.find(params[:group_id] || params[:id])
  end

end

app/views/groups/_form.html.erb
<div>
  <div>
    <%= f.label :banner %>
    <%= f.file_field :banner, class: 'form-control' %>
  </div>
  <br>
  <div>
    <%= f.label :name %>
    <%= f.text_field(:name, class: 'form-control')  %>
  </div>
  <br>
  <div>
    <%= f.label :description %>
    <%= f.text_area(:description, rows: 6, class: 'form-control')  %>
  </div>
  <br>

  <div>
    <%= f.label :privacy %>
    <%= f.select(:privacy, Group.privacies.keys.map { |key| [key.humanize, key] }, { include_blank: 'Please Select Status' }, { class: 'form-control mt-3' }) %>
  </div>
</div>

app/views/groups/edit.html.erb
<div class="main w-50 m-auto">
  <h1>Edit Group</h1>
  <%= form_for @group, url: group_path, method: :patch do |f| %>
    <%= render partial: 'form', locals: {f: f, post: @group} %> <br>
    <%= f.submit "Update",class: 'btn btn-primary' %> <br><br>
  <% end %>
</div>

app/views/groups/index.html.erb
<%= render "layouts/navbar/sharednav" %>
<h1>Group lists</h1>
<div class="w-75 m-auto p-1 text-end">
  <%= link_to 'Create', new_group_path %>
</div>
<%= render "layouts/notification_msg/notify" %> <br>

<div class="table-responsive">
  <table class="table align-middle">
    <thead>
    <tr>
      <th scope="col">Banner</th>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Action</th>
    </tr>
    </thead>
    <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td>
          <%= image_tag group.banner&.url, style: 'height: auto;', class: "w-50" if group.banner? %>
        </td>
        <td>
          <%= group.name %>
        </td>
        <td>
          <%= group.description %>
        </td>
        <td>
          <%= link_to "Join", members_path(group) if policy(group).join? %>
          <%= link_to "View", group_path(group), method: :get %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<br> <br> <br>

app/views/groups/new.html.erb
<div class="main w-50 m-auto">
  <h1>Create Group</h1>
  <%= form_for @group, url: groups_path, method: :post do |f| %>
    <%= render partial: 'form', locals: {f: f, post: @group} %> <br>
    <%= f.submit "Save",class: 'btn btn-primary', style:'margin-buttom: 10px;' %><br><br>
  <% end %>
</div>

app/views/groups/show.html.erb
<%= render "layouts/navbar/sharednav" %>
<div class="text-end">
  <%= link_to " edit ", edit_group_path(@group) if policy(@group).update? %>
  <%= link_to "delete", group_path(@group), method: :delete, data: { confirm: 'Are you sure do you want to delete?' } if policy(@group).update? %>
</div>
<div class="w-100 m-auto text-center p-2"><b><%= @group.name %></b></div>
<%= image_tag @group.banner&.url,style:"object-fit: none;object-position: center; width: 100%; max-height: 300px; margin-bottom: 1rem;" if @group.banner? %>
<div class="w-75 m-auto text-start p-2"> &nbsp;&nbsp;<%= @group.description %></div>
<hr>
<%= link_to "invite", new_member_path%>