config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"
  resources :posts do
    resources :comments
  end
  resources :friendships do
    put :confirm
  end
  resources :friend_requests do
    put :confirm
  end
  resources :friends_list
  resources :groups
  resources :members
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    friends_id = current_user.friendships.confirmed.pluck(:friend_id) + current_user.inverse_friendships.confirmed.pluck(:user_id)
    own_post = current_user.posts.where.not(status: :public_posts)
    public_post = Post.public_post
    friends_post = Post.friends.where(user_id: friends_id)

    @posts =  own_post + public_post + friends_post
  end
end

app/views/home/index.html.erb
<%= render "layouts/navbar/sharednav" %>
<%= render "layouts/notification_msg/notify" %>
<% @posts.each do |post| %>
  <div class="row p-5 m-5">
    <div class=" w-50 m-auto">
      <div class="dropdown text-end">
        <div class="text-center">
          <%= post.user&.email %> <br> <br>
          <%= image_tag post.image.url,style: 'height: auto;', class: "w-50" if post.image? %> <br> <br>
          <%= post.content %>
          <br>
          <br>
          <%= link_to " edit ", edit_post_path(post), class: "text-center border p-2 btn btn-success", style:"width:100px;" if policy(post).update? %>
          <%= link_to "delete", post_path(post),data:{confirm:'Are you sure do you want to delete?'}, method: :delete, class: "text-center border p-2 btn btn-danger", style:"width:100px;" if policy(post).update? %>
        </div>
      </div>
      <br> <br>
      <%= link_to :comments, post_comments_path(post) %>
    </div>
  </div>
<% end %>