config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"
  resources :posts do
    resources :comments
  end
  resources :friendships do
    put :confirm
  end
  resources :friend_requests do
    put :confirm
  end
  resources :friends_list
  resources :groups
  resources :members
end

app/views/layouts/navbar/_sharednav.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Social Media</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active text-decoration-none" %>
        </li>
        <li class="nav-item">
          <%= link_to "Posts", posts_path, class: "nav-link active text-decoration-none" %>
        </li>

        <li class="nav-item">
          <%= link_to "Groups", groups_path, class: "nav-link active text-decoration-none" %>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Friends
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Friends list", friends_list_index_path, class: "dropdown-item text-decoration-none" if user_signed_in? %></li>
            <li><%= link_to "Friend requests", friend_requests_path, class: "dropdown-item text-decoration-none" if user_signed_in? %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Peoples", friendships_path, class: "dropdown-item text-decoration-none" if user_signed_in? %></li>

          </ul>
        </li>

        <li class="nav-item">
          <%= link_to link_to "Logout", destroy_user_session_path, class: "nav-link active text-decoration-none", :method => :delete if user_signed_in? %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>